name: oko
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.9
 - numpy=1.20.*
 - ftfy=5.8
 - pandas=1.5.2
 - scikit-learn=0.24.*
 - pytorch=1.13.*
 - numba=0.54.*
 - matplotlib=3.2.*
 - seaborn=0.11.*
 - scipy=1.10.0
 - jupyterlab
 - regex
 - pip
 - pip:
   - tensorflow_datasets==4.7.*
   - flax==0.6.3
   - optax==0.1.4
   - dm-pix==0.3.4
   - dm-haiku==0.0.9
   - tqdm==4.64.*
   - jaxtyping==0.2.11
   - ml_collections
   - black
   - pyflakes
   - einops
   - codecov
   - pep8
