name: triplet_ssl
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.8
 - numpy=1.19.*
 - ftfy=5.8
 - pandas=1.0.*
 - scikit-learn=0.24.*
 - pytorch=1.11.*
 - torchvision=0.12.*
 - numba=0.53.*
 - matplotlib=3.2.*
 - seaborn=0.11.*
 - jupyterlab
 - regex
 - scipy
 - h5py
 - pip
 - pip:
   - ml_collections 
   - dm-haiku 
   - dm-pix 
   - einops
   - flax
   - optax  
   - jaxlib   
   - tensorflow==2.5.0
   - codecov
   - tqdm
   - pep8
