name: oko
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.8
 - numpy=1.19.*
 - ftfy=5.8
 - pandas=1.0.*
 - scikit-learn=0.24.*
 - pytorch=1.12.*
 - numba=0.54.*
 - matplotlib=3.2.*
 - seaborn=0.11.*
 - jupyterlab
 - regex
 - scipy
 - pip
 - pip:
   - tensorflow==2.9.1
   - tensorflow_datasets==4.7.*
   - jaxlib==0.4.1
   - flax==0.6.3
   - optax==0.1.4
   - dm-pix==0.3.4
   - dm-haiku==0.0.9
   - tqdm==4.64.*
   - ml_collections
   - einops
   - codecov
   - pep8
